services:
  postgres-test:
    image: postgres:17-alpine
    container_name: dashko-test-db
    environment:
      POSTGRES_USER: dashko
      POSTGRES_PASSWORD: dashko
      POSTGRES_DB: dashko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashko"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
