"""add student_rotations and case_submissions tables

Revision ID: 7dcb280f0461
Revises: 54cb65f22443
Create Date: 2026-03-10 01:55:44.190632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dcb280f0461"
down_revision: Union[str, Sequence[str], None] = "54cb65f22443"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_rotations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_rotations_department_id"),
        "student_rotations",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_rotations_student_id"),
        "student_rotations",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "case_submissions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("task_category_id", sa.UUID(), nullable=False),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.Column("proof_url", sa.String(length=1024), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="submission_status",
                create_constraint=True,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_category_id"], ["task_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_submissions_department_id"),
        "case_submissions",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_submissions_student_id"),
        "case_submissions",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_submissions_task_category_id"),
        "case_submissions",
        ["task_category_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_case_submissions_task_category_id"), table_name="case_submissions"
    )
    op.drop_index(op.f("ix_case_submissions_student_id"), table_name="case_submissions")
    op.drop_index(
        op.f("ix_case_submissions_department_id"), table_name="case_submissions"
    )
    op.drop_table("case_submissions")
    op.drop_index(
        op.f("ix_student_rotations_student_id"), table_name="student_rotations"
    )
    op.drop_index(
        op.f("ix_student_rotations_department_id"), table_name="student_rotations"
    )
    op.drop_table("student_rotations")
    # Drop the submission_status enum type
    op.execute("DROP TYPE IF EXISTS submission_status")
    # ### end Alembic commands ###
