"""add supervisor_assignments table

Revision ID: 89b866e8aacc
Revises: 7dcb280f0461
Create Date: 2026-03-10 12:57:17.758786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b866e8aacc'
down_revision: Union[str, Sequence[str], None] = '7dcb280f0461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('assignment_type', sa.Enum('primary', 'department', name='assignment_type', create_constraint=True), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisor_assignments_department_id'), 'supervisor_assignments', ['department_id'], unique=False)
    op.create_index(op.f('ix_supervisor_assignments_student_id'), 'supervisor_assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_supervisor_assignments_supervisor_id'), 'supervisor_assignments', ['supervisor_id'], unique=False)

    # Prevent duplicate primary assignments (supervisor + student, ignoring department)
    op.execute("""
        CREATE UNIQUE INDEX uq_primary_assignment
        ON supervisor_assignments (supervisor_id, student_id)
        WHERE assignment_type = 'primary'
    """)

    # Prevent duplicate department assignments (supervisor + department)
    op.execute("""
        CREATE UNIQUE INDEX uq_department_assignment
        ON supervisor_assignments (supervisor_id, department_id)
        WHERE assignment_type = 'department'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_department_assignment")
    op.execute("DROP INDEX IF EXISTS uq_primary_assignment")
    op.drop_index(op.f('ix_supervisor_assignments_supervisor_id'), table_name='supervisor_assignments')
    op.drop_index(op.f('ix_supervisor_assignments_student_id'), table_name='supervisor_assignments')
    op.drop_index(op.f('ix_supervisor_assignments_department_id'), table_name='supervisor_assignments')
    op.drop_table('supervisor_assignments')
    op.execute("DROP TYPE IF EXISTS assignment_type")
    # ### end Alembic commands ###
